### ISSUE TITLE
Do not stack any site-all files - put 1 into stackedFiles folder.

### ISSUE THREAD

**Issue by chrlaney** [NEONScience/NEON-utilities#10]
Example: phe_perindividual

**Comment by natalie-robinson** [comment]
Hi @chrlaney -

In case it helps, I wrote a little script to:

1) identify the unique sites in a directory of zipped site-folders
2) go through and grab the phe_perindividual (a per-year file) file from the first zipped site-folder for each unique site and append it to a dataframe in R - and then stop looking at zipped folders for that site
3) continue this for all unique sites
4) write out a single file with one set of data for each site (this file could go into the stackedFiles dir).

This was done quickly and is a bit clunky (would need automation implementation) and repetitive, but here it is in case it helps with this task:

library(dplyr)

setwd(('N:/Common/TOS/4Natalie_pheData/NEON_obs-phenology-plant'))

sites <- vector()
for (dirs in list.files(getwd())){
  if (grepl('.basic.',dirs)){
    sites <- c(sites,substring(dirs,10,13))
  }
}
sites <- unique(sites)

newDF <- data.frame(matrix(ncol = 36, nrow = 0))
for (site in sites){
  for (dirs in list.files(getwd())){
    if (grepl('.basic.',dirs) && grepl(site,dirs)){
      dir <- paste(getwd(),dirs,sep='/')
      file <- read.csv(list.files(dir,pattern = "phe_perindividual.basic.", full.names = T),stringsAsFactors = F)
      print(nrow(file))
      newDF <- rbind(newDF,file)
      break
    }
  }
}
names(newDF) <- c('uid','namedLocation','domainID','siteID','plotID','decimalLatitude','decimalLongitude',
'geodeticDatum','coordinateUncertainty','elevation','elevationUncertainty','subtypeSpecification','transectMeter',
'directionFromTransect','ninetyDegreeDistance','sampleLatitude','sampleLongitude','sampleGeodeticDatum',
'sampleCoordinateUncertainty','sampleElevation','sampleElevationUncertainty','addDate','editedDate','individualID',
'taxonID','scientificName','identificationQualifier','taxonRank','growthForm','vstTag','samplingProtocolVersion',
'measuredBy','identifiedBy','recordedBy','remarks','dataQF')


write.csv(newDF,paste('stackedFiles','phe_perindividual.csv',sep='/'),row.names=F,na='')

**Comment by chrlaney** [comment]
@cklunch @natalie-robinson @scelmendorf @sokole I think(?) the latest push fixes the problem. Unfortunately, for now it relies on a table type csv file that shows whether a table is site-date, site-all, etc. that has to be updated as new data products are added. Will look into using the dps database in the future. Please test for now with various data products and let me know if you have any problems.
