### ISSUE TITLE
Allow zipsByUri() to accept R objects as input

### ISSUE THREAD

**Issue by lstanish** [NEONScience/NEON-utilities#103]
Currently, the zipsByUri() function takes in NEON data tables that are downloaded and merged using stackByTable(). However, for an automated data processing workflow it is preferable to be able to use the R objects created by loadByProduct() as inputs to zipsByUri() rather than having to download the files.

For a current project, we are designing the workflow to use loadByProduct() to create local R objects of the NEON data tables containing the URIs. These files are then downloaded so that they match the required format of zipsByUri(), e.g. the metadata table containing the URI's is downloaded with the required file name format, and the variables file. We then run zipyByUri() on these downloaded files. 

Ideally we could cut out this downloading step and just go straight from loadByProduct to zipsByUri(). We'd like to be able to convert the list object created by loadByProduct() into a data.frame and use that as the input to zipsByUri().

**Comment by cklunch** [comment]
zipsByURI() can accept R objects as inputs as of version 2.1.4, now on CRAN.
