### ISSUE TITLE
download specific table(s) with loadByProduct rather than all tables

### ISSUE THREAD

**Issue by jcoloso** [NEONScience/NEON-utilities#108]
I'm using `loadByProduct` to download surface water chemistry data (DP1.20093.001), but it is quite slow. I'm only using the swc_domainLabData table and was hoping there could be a way to get just that table without first having to download and stack all the tables.

**Comment by cklunch** [comment]
@jcoloso This is currently in getDatatable(), and will be moved to loadByProduct() in neonUtilities 2.0. See #106 for current issues in getDatatable().

**Comment by jcoloso** [comment]
Great! I forgot about getDatatable() as I'm so used to using loadByProduct(). I'll give it a try. I'm looking forward for that functionality to be added to loadByProduct().
