### ISSUE TITLE
dataStackR issue with Ground beetles sampled from pitfall traps

### ISSUE THREAD

**Issue by sokole** [NEONScience/NEON-utilities#11]
@chrlaney 

I get this error when trying to stack Ground beetles sampled from pitfall traps:

> cannot open file 'data/table_types.csv': No such file or directoryError in file(file, "rt") : cannot open the connection

**Comment by sokole** [comment]
I'm not sure what it's looking for that it's not finding. Would it be an issue of some subdirectories don't have all the tables?

**Comment by chrlaney** [comment]
Thanks for the alert message @sokole - It looks like there was an sync issue for that file. I've fixed it but now dealing with another bug. I'll let you know when fixed :)

**Comment by chrlaney** [comment]
@sokole - I think it's fixed. Can you reinstall on your local machine and try it out?

**Comment by sokole** [comment]
@chrlaney just reinstalled and tried stacking stream discharge and got the same error. I'll try with some other data sets and let you know if I learn anything new.

**Comment by chrlaney** [comment]
argh. Thanks though!

**Comment by sokole** [comment]
FYI, I seem to get the same error with any data set I download off the portal at the moment.

**Comment by chrlaney** [comment]
Which ones are those?

**Comment by sokole** [comment]
Tick counts, Stream discharge, and Macroinvertebrate collection are the ones I've tried today.

**Comment by chrlaney** [comment]
Thanks. I'll start troubleshooting with these.

**Comment by sokole** [comment]
Just tried plant phenology and that one no longer works either. 

It successfully unpacks the zipped files for all these data products, if that helps. It seems to bork in the stacking part of the function.

**Comment by chrlaney** [comment]
I think because the table_types.csv file is still incomplete. I'm working on it. :)

**Comment by lstanish** [comment]
@chrlaney @sokole Just an FYI that I tried to stack mosquitoes and there's the same issue. Will check back later!

**Comment by chrlaney** [comment]
fixed in release v0.1.3 pecan
