### ISSUE TITLE
Unable to update NEON-utilities in Cyverse

### ISSUE THREAD

**Issue by ocallahana** [NEONScience/NEON-utilities#118]
**Function**
The issue is with updating and installing the newest version (2.1) of neonUtilities. 

**Describe the bug**
I tried using `install.packages("neonUtilities")` in Cyverse in an RStudio instance, but the only version of neonUtilities that will download is 1.3.5. I uninstalled and tried to reinstall and use update commands with no luck. In particular, I tried to manually download the newest package using `devtools::install_github("NEONScience/NEON-utilities")` but received this error: 

> "Error: Failed to install 'unknown package' from GitHub: HTTP error 404. Not Found. Did you spell the repo owner (`NEONScience`) and repo name (`NEON-utilities`) correctly? - If spelling is correct, check that you have the required permissions to access the repo."

**To Reproduce**
`install.packages("neonUtilities")`

**Expected behavior**
I expected the newest package (2.1) of neonUtilities to download, but only version 1.3.5 will download. 

**System (please complete the following information):**
- RStudio Container on Cyverse (https://de.cyverse.org/apps/de/b25cfd56-041a-11eb-a64d-008cfa5ae621) that uses the Neon API

**Additional context**
I have the R package neonMicrobe installed, of which neonUtilities is a dependency, so I am wondering if this could be messing it up?

**Comment by cklunch** [comment]
@ocallahana I'm not able to access the container on CyVerse, but I'm guessing the default repo for package installation is somewhere local, so it's not up to date with the latest versions on CRAN. You can see where the system is looking by running getOption("repos"). NULL means local.

You can force it to look elsewhere by modifying the repo argument, as in: 
`install.packages("neonUtilities", repos="https://cloud.r-project.org")` 
But usually when versions are constrained within a container, there's a reason - are there other users of the container you're working in? You may want to consult with them before updating the package version, although neonUtilities 1.3.5 is quite out of date, and won't work correctly in some cases, particularly around data download.

If updating is fine for all users, but you prefer to install from GitHub, the install command should be:
`devtools::install_github("NEONScience/NEON-utilities/neonUtilities")`
The package is a subdirectory in the repo.

I'm not familiar with the neonMicrobe package, but a package that depends on neonUtilities shouldn't have any impact on this. If you're in touch with the package developer/maintainer, it would be great if they submitted it to the [NEON Code Hub](https://www.neonscience.org/resources/code-hub) so more people can find it!

**Comment by ocallahana** [comment]
Hi Claire,

Thank you so much for the help!

Thanks,
Alexis

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
