### ISSUE TITLE
neonDataStackR broken -- issue with RMySQL dependency

### ISSUE THREAD

**Issue by sokole** [NEONScience/NEON-utilities#12]
when I try to install local, I get the following error:

`> devtools::install_local('C:/Users/esokol/Desktop/neonDataStackR')`

`Installing neonDataStackR`
`"C:/PROGRA~1/R/R-34~1.1/bin/x64/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  "C:/Users/esokol/AppData/Local/Temp/Rtmp0kKa0D/file4ad07c76763/neonDataStackR"  \
  --library="C:/Users/esokol/Documents/R/win-library/3.4" --install-tests `

`* installing *source* package 'neonDataStackR' ...`
`** R`
`** data`
`*** moving datasets to lazyload DB`
`** preparing package for lazy loading`
`Warning: package 'RMySQL' was built under R version 3.4.2`
`Error in .local(drv, ...) : 
  Failed to connect to database: Error: Access denied for user 'root'@'10.200.14.192' (using password: YES)`

`Error : unable to load R code in package 'neonDataStackR'`
`ERROR: lazy loading failed for package 'neonDataStackR'`
`* removing 'C:/Users/esokol/Documents/R/win-library/3.4/neonDataStackR'`
`Installation failed: Command failed (1)`

It seems it's trying to connect to a server I don't have credentials for on the install?

**Comment by sokole** [comment]
@chrlaney I think @tapchesney had this issue too?

**Comment by cklunch** [comment]
@sokole Do you get the same result if you use install_github?

**Comment by sokole** [comment]
yep

**Comment by sokole** [comment]
this is the last commit (from Oct 6) for the package that works for me
9d16d990c7c174b867816ce3d4c8c39e1fda53d6

**Comment by chrlaney** [comment]
Could you please try again? I just wrapped the code for updating table_types.rda into a function, hopefully will not require installation of RMySQL.

**Comment by tapchesney** [comment]
Sorry for the late reply, @sokole. Yes, I had the exact same issue. I manually installed RMySQL and it still gave the error. Then, magically, I reinstalled the neonDataStackR a day later and it worked. Looks like @chrlaney made some updates. I hope it works!

**Comment by sokole** [comment]
@chrlaney success! Thanks!

**Comment by chrlaney** [comment]
@sokole @tapchesney Thanks for persisting!
