### ISSUE TITLE
The 2022 AOP data has a .json error and cannot be downloaded

### ISSUE THREAD

**Issue by bw4sz** [NEONScience/NEON-utilities#124]
**Function**
The byFileAOP cannot be downloaded. I was attempting to download all 2022 aop data using a script I have used for several years. It works for 2021 data, but 2021 has a html/json error.

**Describe the bug**
**To Reproduce**

```

> version
               _                           
platform       x86_64-apple-darwin17.0     
arch           x86_64                      
os             darwin17.0                  
system         x86_64, darwin17.0          
status                                     
major          4                           
minor          0.3                         
year           2020                        
month          10                          
day            10                          
svn rev        79318                       
language       R                           
version.string R version 4.0.3 (2020-10-10)
nickname       Bunny-Wunnies Freak Out  

library(neonUtilities)

#This works
byFileAOP(dpID = "DP3.30010.001" ,year = "2021", site="SERC")

# This yields
byFileAOP(dpID = "DP3.30010.001" ,year = "2022", site="SERC")
```

```
Error: lexical error: invalid char in json text.
<!doctype html><html lang="en">
  (right here) ------^
```

neonUtilities_2.1.4 

**Additional context**
I have also tried on a linux HPC system, same error.

**Comment by cklunch** [comment]
The /data endpoint of the NEON API is erroring out on some 2022 AOP data. We're investigating.

**Comment by cklunch** [comment]
This issue is affecting essentially all 2022 AOP data. We're working on resolving, more details [here](https://www.neonscience.org/impact/observatory-blog/aop-data-availability-notification).

I'm also making an update to neonUtilities so that if this happens again, the error message will be a little more informative.

**Comment by cklunch** [comment]
The AOP data access problem is resolved. The update to the byFileAOP()/byTileAOP() error message will be in the next version.
