### ISSUE TITLE
fail to extract DP3.30015.001 product from NIWO site using byTileAOP

### ISSUE THREAD

**Issue by huiqi-wang** [NEONScience/NEON-utilities#134]
**Function**
Which of the functions in the neonUtilities package is this bug found in?
byTileAOP
**Describe the bug**
I used this code, but it failed but the data is shown available from the data portal.

byTileAOP(dpID="DP3.30015.001", site=plotid, year="2020", 
          easting=veg$adjEasting[which(veg$plotID==plotid)], 
          northing=veg$adjNorthing[which(veg$plotID==plotid)],
          check.size=FALSE, savepath=wd)

error:
Error in byTileAOP(dpID = "DP3.30015.001", site = plotid, year = "2020",  : 
  There are no data at the selected site and year.

**To Reproduce**
What function inputs revealed the bug?

byTileAOP(dpID="DP3.30015.001", site=plotid, year="2020", 
          easting=veg$adjEasting[which(veg$plotID==plotid)], 
          northing=veg$adjNorthing[which(veg$plotID==plotid)],
          check.size=FALSE, savepath=wd)

**Expected behavior**
I expect it download the data and I can use it to plot the canopy height model

**System (please complete the following information):**
 - OS Version: [e.g. 22]
 - R Version: [e.g. 3.5.1]

mac OS Sonoma Version 14.3.1
R version: Version 2024.04.1+748 (2024.04.1+748) 

**Additional context**

I follow the tutorial here and just replace the site ID: https://www.neonscience.org/resources/learning-hub/tutorials/tree-heights-veg-structure-chm

**Comment by cklunch** [comment]
@huiqi-wang The issue is the plotid variable. In the code snippet you included, I can't see its value, but the same value wouldn't work as the site input and in the easting/northing inputs. site= should be a 4-letter code for a NEON site, e.g. "WREF", "NIWO", etc. The plotID in veg$plotID== should have the plot number as well as the site code, something like "WREF_005" or "NIWO_007".

**Comment by huiqi-wang** [comment]
The plot id I used is: plotid <- "NIWO_017"

**Comment by cklunch** [comment]
@huiqi-wang OK, in that case your function call should be:
```
byTileAOP(dpID="DP3.30015.001", site="NIWO", year="2020", 
          easting=veg$adjEasting[which(veg$plotID==plotid)], 
          northing=veg$adjNorthing[which(veg$plotID==plotid)], 
          check.size=FALSE, savepath=wd)
```

**Comment by huiqi-wang** [comment]
Oh cool!!! It works!!!! Thanks so much! I appreciate it~

**Comment by huiqi-wang** [comment]
I have another question, it looks like that each plotid has its own tif, so I have to change it manually when processing data for each plot_id. I am wondering if there is a function or a file documenting the plot_id and its tif name. Thanks!

**Comment by cklunch** [comment]
@huiqi-wang There can be multiple plots in one tile. The easiest way to get all of the tiles for all of the plots is not to specify the plot in the download, like this:
```
byTileAOP(dpID="DP3.30015.001", site="NIWO", year="2020", 
          easting=veg$adjEasting, 
          northing=veg$adjNorthing, 
          check.size=FALSE, savepath=wd)
```

Then you can line up the vegetation structure data with the remote sensing data via the easting and northing coordinates, as shown in the tutorial.

**Comment by huiqi-wang** [comment]
it works!! Thanks so much for the help!
