### ISSUE TITLE
neonDataStackR - stackByTable - add parameter to retain vs delete unzipped files

### ISSUE THREAD

**Issue by scelmendorf** [NEONScience/NEON-utilities#15]
neonDataStackR - stackByTable would be nice to have an option/default (e.g. saveUnzippedFiles = T/F) of not saving the unzipped but still unstacked files. I think the most common use case is to use ONLY the stacked files after running successfully.

**Comment by chrlaney** [comment]
Added this parameter to stackByTable(); it will currently remove all unzipped monthly data folders, and no EML or readme files will be retained.
