### ISSUE TITLE
stackByTable not stacking site-all tables

### ISSUE THREAD

**Issue by kjones13** [NEONScience/NEON-utilities#18]
Hello, I have a folder containing data zip files from multiple sites, each zip contains 1-2 site-date files and 1 site-all file . If I run the stackByTable function, I get tables containing all data, from all sites for the two site-date tables, but the site-all table only contains data pertaining to only one site, BART. BART is the first site in the list of zip folders, so it appears the stackByTable function may only be looking for site-all table once rather than once per site. @chrlaney, @cklunch can you help?

Thanks!

**Comment by chrlaney** [comment]
@kjones13 - sorry for the delay on the fix. Please reinstall and try again, and let me know if you run into any issues!

**Comment by kjones13** [comment]
it works! Thank you for this fix @chrlaney!
