### ISSUE TITLE
StackByTable not working with DP1.20093

### ISSUE THREAD

**Issue by mjones01** [NEONScience/NEON-utilities#19]
@cklunch @chrlaney  I am working with the surface water chemistry data and getting the following error when I run the stackByTable function.  I am able to stack other Data Products (like DP1.00002) so it appears to be an issue with the Data Product set up.

> stackByTable("data/NEON_chem-surfacewater.zip")
Unpacked  NEON.D11.PRIN.DP1.20093.001.2016-10.basic.20171212T170858Z.zip
Unpacked  NEON.D11.PRIN.DP1.20093.001.2016-11.basic.20171212T194316Z.zip
*(removed extra lines with files)*
Error in file(file, "rt") : cannot open the connection
In addition: Warning message:
In file(file, "rt") : cannot open file 'NA': No such file or directory

**Comment by chrlaney** [comment]
@mjones01 I just tried it on my end and it works fine (expanded package, all data available). Did you freshly install the neonDataStackR package?

**Comment by mjones01** [comment]
@chrlaney Yes. When I ran into the problem I delete my previous version and reinstalled the package this evening from GitHub.  I should also have mentioned that when I get the error, I also get an unzipped dir. which contained a stackedFiles subdir but the stackedFiles dir only contains validation.csv and variables.csv files. Any thoughts on how I could trouble shoot on my end?

**Comment by mjones01** [comment]
@chrlaney I tried this again this morning on an entirely new set up (Windows 10 with new installs of R, RStudio, & neonDataStackR this morning).  Exact same error message for DP1.20093 and again a successful stack of DP1.10055 (Plant Pheno) data. This is with data downloaded from the portal and not pulled through the API, if that matters. I also tried a data set from ARIK with the same error messages.
If you'd like to try it with the same data you can access the download on this workshop page (http://www.neonscience.org/neon-data-training-20180118; note that the download is exactly the same file as downloaded directly from portal).

**Comment by chrlaney** [comment]
@mjones01 - I've made an update of table_types.rda in the github repo. Could you please try 
devtools::install_github("NEONScience/NEON-utilities/neonDataStackR", force = TRUE)
and then try running stackByTable() once more? If it still doesn't work, could you stop by with your computer?

**Comment by mjones01** [comment]
Resolved.  Thank you for your help.

**Comment by chrlaney** [comment]
Note for future - still unclear why this occurred. In order to get the package to install correctly, the environment needed to be cleared, and then RStudio restarted.
