### ISSUE TITLE
Add option for quiet/quietly or silent=T & progress bar

### ISSUE THREAD

**Issue by scelmendorf** [NEONScience/NEON-utilities#22]
Just a suggestion for an aesthetic enhancement, but would be nice to add a progress bar and an option to suppress all the messages. Specifically thinking of the screen of red 'Joining by .....' in stackByTable' and the screen of red 'Trying url' in zips by product.
 I would make this the default.

**Comment by chrlaney** [comment]
Silent is the de facto mode now, with progress bars. Later revision will include piping messages to a log file.
