### ISSUE TITLE
If only 1 instance of a data table, does not copy into the stackedFiles folder

### ISSUE THREAD

**Issue by chrlaney** [NEONScience/NEON-utilities#3]
But it says that it stacked the table. Bug found in recent deployment of DP1.20066 aquatic plant clip harvest. Solution: if only one file with a given table, copy into stackedFiles folder.

**Comment by chrlaney** [comment]
Fixed with commit https://github.com/NEONScience/NEON-utilities/commit/9d8630310ded20c203ccebc710f82f65a6f09209

**Comment by sokole** [comment]
I re-installed the package today, then stacked the aquatic cell counts data and this bug seemed to persist.

**Comment by chrlaney** [comment]
This is a different bug. Closing this issue and creating issue #6.
