### ISSUE TITLE
Select tiles based on extent for byFileAOP

### ISSUE THREAD

**Issue by bw4sz** [NEONScience/NEON-utilities#30]
First day with the NEON API. All feedback welcome. Couples questions as I get started.

I'm looking to download the high resolution camera imagery (DP1.30010.001), the lidar point cloud, and the hyperspectral data for a single site (OSBS). Is there anyway to select a set of tiles based on the extent of my field-collected data. While I may eventually need the full site scale, given the large data sizes, it would be useful to be able to select a subset of tiles.

Thanks.

**Comment by markkessel** [comment]
The Harris ENVI software (NEON has some licenses) provides capabilities of subsetting imagery, lidar and hyperspectral datasets by extent (e.g., defined by shapefile), but I'm not sure that gets you closer to where you need to be.

thanks,
Mark

**Comment by bw4sz** [comment]
Sorry, never closed this. I downloaded fullsite and then cropped using R.
