### ISSUE TITLE
stackByTable only works if library is loaded

### ISSUE THREAD

**Issue by scelmendorf** [NEONScience/NEON-utilities#34]
does not work:
neonUtilities::stackByTable(dpID="DP1.10055.001", paste0(getwd(), "/filesToStack10055"), folder=T)

Error in stackDataFiles(savepath) : object 'table_types' not found
In addition: Warning message:
In data("table_types") : data set ‘table_types’ not found

works:
library(neonUtilities)
neonUtilities::stackByTable(dpID="DP1.10055.001", paste0(getwd(), "/filesToStack10055"), folder=T)

seems like stackByTable can't find table_types file unless the whole library is loaded?

**Comment by cklunch** [comment]
A while back we changed the way table_types is stored in the package, and I'm no longer able to replicate this bug, so I think this is resolved!
