### ISSUE TITLE
Naming of variable and validation file

### ISSUE THREAD

**Issue by gklarenberg** [NEONScience/NEON-utilities#36]
I wrote a loop (in R) to extract various data files from various locations (JERC, OSBS and DWNY in my case), and use the NEONutilities to put all the zip files together in one files. However, I am saving all the files in one folder associated with the location, and because the variable and validation files are named the same for every data product ("variable.csv" and "validation.csv"), they get overwritten. So I only end up with those for the last data file. Would it be possible to also add a data identifiers to these file names?

**Comment by cklunch** [comment]
Updated in neonUtilities v1.3.3 - variables, validation, readme, and sensor_positions files now have the data product number appended to the file name, e.g. variables_10098.
