### ISSUE TITLE
zipsByProduct: 'names' attribute [3] must be the same length as the vector [1]

### ISSUE THREAD

**Issue by Danielslee51** [NEONScience/NEON-utilities#38]
There seems to be an error that happens at random with the `zipsByProduct` function, where seemingly valid site and product combos return the error `'names' attribute [3] must be the same length as the vector [1]`. For example:
• "DP1.10020.001" with "HEAL"
• "DP1.00003.001" with "ABBY"
Not sure if this is related to the function, or the availability of the data products. If it is something about the products and not the function, hopefully it can give a better error message.

Thanks!

**Comment by cklunch** [comment]
Modified error messaging is merged to master.
