### ISSUE TITLE
Add an interactive example with Binder

### ISSUE THREAD

**Issue by matthewfeickert** [NEONScience/NEON-utilities#43]
It would be very cool if there was an interactive example of how to use `neonUtilities` with NEON's open data using the [IRkernel](https://github.com/IRkernel/IRkernel) and [Binder](https://mybinder.org/).

Binder is incredible, so I highly recommend learning more about it on their [docs](https://mybinder.readthedocs.io/en/latest/) (and maybe watching @betatim's [JupyterCon 2018 talk on it](https://youtu.be/MhyzZAbOCGw)).

If you like the idea but need some help getting started you can checkout my [R in Jupyter with Binder example repo](https://github.com/matthewfeickert/R-in-Jupyter-with-Binder) and I am willing to answer questions and help out on the PR.

**Comment by cklunch** [comment]
Agreed, this would be great! At the moment we're primarily limited by staff time, but we hope to start making interactive notebooks eventually. Thanks for the helpful links.

In the meantime, we do have non-interactive instructions and examples here: https://www.neonscience.org/neonDataStackR

**Comment by matthewfeickert** [comment]
> What did you have in mind for the Binder example?

Just something that demos the API for the library with practical use case examples. So since the "[Use the neonUtilities Package to Access NEON Data](https://www.neonscience.org/neonDataStackR)" example exists just Binderizing that would probably be a good start (and then maybe doing some trivial visualizations and toy analysis).

Given that [it seems that the tutorial source is not on GitHub](https://github.com/search?q=This+package+is+intended+to+provide+a+toolbox+of+basic+functionality+for+working+with+NEON+data.+It+currently+contains+the+functions+listed+above%2C+but+it+is+under+development+and+more+will+be+added+in+the+future.&type=Code) is it somewhere other then the NEON GitHub org where it has actually been versioned? Or would you recommend just [download the R source](https://www.neonscience.org/sites/default/files/code/R/neonUtilities/neonUtilities.R) and then just add and modify it in the PR?

**Comment by matthewfeickert** [comment]
Closing as migrated to [NEONScience/NEON-Data-Skills Issue #405](https://github.com/NEONScience/NEON-Data-Skills/issues/405).
