### ISSUE TITLE
Undocumented File Deletion Behavior: stackByTable() deletes .R code files (and other files) if in same path

### ISSUE THREAD

**Issue by cflagg** [NEONScience/NEON-utilities#47]
stackByTable() will delete all files, including an .R/.Rmd file, if the executing file is in the same path specified by argument `savepath`. This is not intuitive or obvious behavior. 

This is not documented anywhere in the [tutorial](https://www.neonscience.org/neonDataStackR) nor in the CRAN documentation i.e. the words "delete", "remove", and/or "discard" do not appear anywhere in the text. 

### Example:

For a path: "/analyses"

If I have an R file "/analyses/grab_data.R"

```
# folder structure -- deletes files
analyses
--grab_data.R
```

And execute

```
# R file IN folder "analyses"
path <- "~/analyses/"

getPackage(dpID = "DP1.10055.001", site_code = "SOAP", year_month = "2018-09", savepath = path, package = 'basic')

stackByTable(filepath = path, folder = TRUE, saveUnzippedFiles = TRUE)
```

Immediately deletes the R/Rmd file. 

Using the following folder structure is safer, but again not specified or obvious: 

```
# folder structure -- deletes files
analyses
--grab_data.R
--data/ 
```

```
# R file IN folder "analyses"
path <- "~/analyses/data/"

getPackage(dpID = "DP1.10055.001", site_code = "SOAP", year_month = "2018-09", savepath = path, package = 'basic')

stackByTable(filepath = path, folder = TRUE, saveUnzippedFiles = TRUE)
```

**Comment by cklunch** [comment]
@cflagg Thanks for the heads up about this! Now fixed on GitHub, hopefully released to CRAN shortly.

**Comment by cklunch** [comment]
The fix is now on CRAN.
