### ISSUE TITLE
neonUtilities Install Errors and Warnings

### ISSUE THREAD

**Issue by keramsey** [NEONScience/NEON-utilities#56]
**Function**
Which of the functions in the neonUtilities package is this bug found in?
no package called 'hms'

**Describe the bug**
I receive the following errors when attempting to install neonUtilities:
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called 'hms'
ERROR: lazy loading failed for package 'neonUtilities'
* removing 'C:/Users/<user>/Documents/R/win-library/3.4/neonUtilities'

The downloaded source packages are in
        ‘C:\Users\<user>\AppData\Local\Temp\RtmpSGzwFh\downloaded_packages’
Warning messages:
1: running command '"C:/PROGRA~1/R/R-34~1.0/bin/x64/R" CMD INSTALL -l "C:\Users\<user>\Documents\R\win-library\3.4" C:\Users\<user>\AppData\Local\Temp\RtmpSGzwFh/downloaded_packages/hms_0.5.0.tar.gz' had status 1 
2: In install.packages("neonUtilities") :
  installation of package ‘hms’ had non-zero exit status
3: running command '"C:/PROGRA~1/R/R-34~1.0/bin/x64/R" CMD INSTALL -l "C:\Users\<user>\Documents\R\win-library\3.4" C:\Users\<user>\AppData\Local\Temp\RtmpSGzwFh/downloaded_packages/neonUtilities_1.3.1.tar.gz' had status 1 
4: In install.packages("neonUtilities") :
  installation of package ‘neonUtilities’ had non-zero exit status
**To Reproduce**
What function inputs revealed the bug?
install.packages('neonUtilities')
library(neonUtilities)
**Expected behavior**
I expected that neonUtilities would finish installing without errors.
**System (please complete the following information):**
 - OS: Windows 7 Professional x64
 - OS Version: Service pack 1 
 - R Version: 3.4.0

**Additional context**

**Comment by cklunch** [comment]
It looks to me like this is a problem with the paths on your machine. My best guess is that it's trying to install from a location other than CRAN, and can't find hms there. Try running `options()$repos` to see where the global option for repositories is pointing, and if it isn't CRAN, redirect it there.

**Comment by keramsey** [comment]
Hi,

I edited the paths to remove my account name. I picked a CRAN
repository in Texas from with R.

I reran the install and picked the 0-cloud CRAN repository and I
receive the following output:
> install.packages('neonUtilities')
Installing package into
‘C:/Users/kramsey.JRN/Documents/R/win-library/3.4’
(as ‘lib’ is unspecified)
--- Please select a CRAN mirror for use in this session ---

  There is a binary version available but the source version is later:
              binary source needs_compilation
neonUtilities  1.2.1  1.3.1             FALSE

installing the source package ‘neonUtilities’

trying URL
'https://cloud.r-project.org/src/contrib/neonUtilities_1.3.1.tar.gz'
Content type 'application/x-gzip' length 125297 bytes (122 KB)
downloaded 122 KB

* installing *source* package 'neonUtilities' ...
** package 'neonUtilities' successfully unpacked and MD5 sums checked
** R
** inst
** preparing package for lazy loading
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()),
versionCheck = vI[[j]]) : 
  there is no package called 'hms'
ERROR: lazy loading failed for package 'neonUtilities'
* removing
'C:/Users/kramsey.JRN/Documents/R/win-library/3.4/neonUtilities'

The downloaded source packages are in
       
‘C:\Users\kramsey.JRN\AppData\Local\Temp\RtmpsT0MT4\downloaded_packages’
Warning messages:
1: running command '"C:/PROGRA~1/R/R-34~1.0/bin/x64/R" CMD INSTALL -l
"C:\Users\kramsey.JRN\Documents\R\win-library\3.4"
C:\Users\kramsey.JRN\AppData\Local\Temp\RtmpsT0MT4/downloaded_packages/neonUtilities_1.3.1.tar.gz'
had status 1 
2: In install.packages("neonUtilities") :
  installation of package ‘neonUtilities’ had non-zero exit status

Here is the output of the  options($repos) command on the second
attempt:
                                   CRAN                                
             CRANextra
"https://cloud.r-project.org" "http://www.stats.ox.ac.uk/pub/RWin"

Do I need to update R?

Thanks.

Ken


>>> Claire Lunch <notifications@github.com> 2019-08-14 12:50 PM >>>
It looks to me like this is a problem with the paths on your machine.
My best guess is that it's trying to install from a location other than
CRAN, and can't find hms there. Try running `options()$repos` to see
where the global option for repositories is pointing, and if it isn't
CRAN, redirect it there.

**Comment by cklunch** [comment]
Hmm. You may end up needing to update to R 3.6, but it also might be that the repos you're using arent fully up to date. Try this:
`install.packages("neonUtilities", repos="https://cran.rstudio.com/")`

**Comment by keramsey** [comment]
I tried installing the hms package and received an error stating that a dependent package, vctrs, needed to be 0.2.0 or higher but the installed version was 0.1.0. I tried installing vctrs using type=source and it failed with errors. Perhaps, I need devtools? I used the cran.rstudio.com repository when installing the packages.

I then updated R from 3.4.0 to 3.6.1 and installed neonUtilities. It seems to load the neonUtilities library without errors. I assume that neonUtilities installed properly.

Is there a way to test the installation?

Feel free to close this ticket.


>>> Claire Lunch <notifications@github.com> 2019-08-14 02:37 PM >>>
Hmm. You may end up needing to update to R 3.6, but it also might be that the repos you're using arent fully up to date. Try this:
`install.packages("neonUtilities", repos="https://cran.rstudio.com/")`

**Comment by keramsey** [comment]
Updating to R 3.6.1 seems to have fixed my installation issues.

**Comment by cklunch** [comment]
Great, glad to hear it!
