### ISSUE TITLE
have DP1.30003.001 work with byTileAOP() function

### ISSUE THREAD

**Issue by MarconiS** [NEONScience/NEON-utilities#58]
Hi,
thanks for working on this package! Right now it is possible to download point cloud data only for the entire site and not by tile. Despite DP1.30003.001 is indeed mosaic, it falls in the category of L1 products, and hence the function will not download them. I think it would be handy to have it unflagged and considered as DP3.

Best,
Sergio

**Comment by cklunch** [comment]
@MarconiS Thanks for alerting me to this! I'll fix it in the next release.

**Comment by cklunch** [comment]
This is fixed on GitHub, if you install from here it should work fine! I have several other updates I want to make in the next release, so I'll leave this issue open until I do the next CRAN submission.

**Comment by MarconiS** [comment]
This is awesome! I’ll go ahead and include a function in a package I am working on to retrieve AOP data at TOS plot level. Let me know if at any point it can be useful for you to chat and see if you want to integrate them in NEON-utilities :)

Thanks!

On Oct 4, 2019, at 5:36 PM, Claire Lunch <notifications@github.com<mailto:notifications@github.com>> wrote:


EXTERNAL EMAIL: Exercise caution with links and attachments.




This is fixed on GitHub, if you install from here it should work fine! I have several other updates I want to make in the next release, so I'll leave this issue open until I do the next CRAN submission.

**Comment by cklunch** [comment]
@MarconiS This is fixed in version 1.3.2, now released on CRAN. Thanks!
