### ISSUE TITLE
Potential for infinite loops in byTileAOP

### ISSUE THREAD

**Issue by mbjoseph** [NEONScience/NEON-utilities#69]
**Function**

byTileAOP

**Describe the bug**

I'm running into an infinite loop when data downloads result in errors. I believe this may be due to this while loop: https://github.com/NEONScience/NEON-utilities/blob/master/neonUtilities/R/byTileAOP.R#L242-L261

If the data download always results in an error, there is no way to exit the while loop.

**To Reproduce**

```r
byTileAOP(dpID = "DP3.30006.001", site = "ORNL", year = "2016", 
            easting = 744000, northing = 983000, check.size = FALSE)
```

```
Downloading files totaling approximately 645.7 MB MB
Downloading 1 files
  |                                                                                                                                           |   0%File could not be downloaded. URLs may have expired. Getting new URLs.
Continuing downloads.
File could not be downloaded. URLs may have expired. Getting new URLs.
Continuing downloads.
File could not be downloaded. URLs may have expired. Getting new URLs.
Continuing downloads.
File could not be downloaded. URLs may have expired. Getting new URLs.
Continuing downloads.
File could not be downloaded. URLs may have expired. Getting new URLs.
Continuing downloads.
File could not be downloaded. URLs may have expired. Getting new URLs.
Continuing downloads.
File could not be downloaded. URLs may have expired. Getting new URLs.
Continuing downloads.
```
and so on.

**Expected behavior**

I expected this function to download a data file, or upon failure, fail somewhat more gracefully (e.g., by trying the download the file some finite number of times). It would be my expectation that you probably don't want to retry to download a file more than a few times if there are errors arising. 

**System (please complete the following information):**
 - OS: [e.g. iOS] Ubuntu
 - OS Version: [e.g. 22] 18.04
 - R Version: [e.g. 3.5.1] 3.6.2

```
R version 3.6.2 (2019-12-12)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.3 LTS

Matrix products: default
BLAS/LAPACK: /opt/intel/compilers_and_libraries_2018.2.199/linux/mkl/lib/intel64_lin/libmkl_rt.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8   
 [6] LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] neonUtilities_1.3.2

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.3       rstudioapi_0.10  magrittr_1.5     hms_0.5.2        tidyselect_0.2.5 R6_2.4.1         rlang_0.4.2      stringr_1.4.0    httr_1.4.1      
[10] dplyr_0.8.3      tools_3.6.2      packrat_0.5.0    gtools_3.8.1     digest_0.6.23    assertthat_0.2.1 tibble_2.1.3     lifecycle_0.1.0  crayon_1.3.4    
[19] purrr_0.3.3      readr_1.3.1      tidyr_1.0.0      vctrs_0.2.1      curl_4.3         zeallot_0.1.0    glue_1.3.1       gdata_2.18.0     stringi_1.4.3   
[28] downloader_0.4   compiler_3.6.2   pillar_1.4.3     backports_1.1.5  jsonlite_1.6     lubridate_1.7.4  pkgconfig_2.0.3 
```

## Additional context

I haven't tested it, but this might also affect `byFileAOP` which has a similar while loop: https://github.com/NEONScience/NEON-utilities/blob/master/neonUtilities/R/byFileAOP.R#L132-L153

**Comment by cklunch** [comment]
@mbjoseph 
Thanks for letting us know about this! I think you've correctly diagnosed the source of the problem, it shouldn't be hard to fix.

Usually this wouldn't be happening, because the download functions check against data availability before trying to download anything, but we've been having some odd errors recently with inconsistency between actual and reported availability. Hopefully those will be resolved, but we'll make this code robust to the situation anyway.

**Comment by cklunch** [comment]
@mbjoseph This is now resolved on GitHub. We've also refreshed AOP availability, so the underlying problem in the API that was leading to this situation is also resolved. I'll close the issue once the new release goes to CRAN, we're planning on ~end of this month.

**Comment by cklunch** [comment]
This fix is now on CRAN.
