### ISSUE TITLE
All folders are deleted during cleanBy

### ISSUE THREAD

**Issue by NateMietk** [NEONScience/NEON-utilities#72]
All folders during the cleanBy function are deleted, regardless if they are custom folders.   This needs to be updated such that only folders generated by the unzipping are deleted.

**Comment by cklunch** [comment]
@NateMietk When you're working on this one, can you also look into making the deletion work correctly with the avg= parameter? Right now it doesn't delete if you specify an averaging interval.

**Comment by cklunch** [comment]
This is now resolved on GitHub. Issue will be closed after the next CRAN release.

**Comment by cklunch** [comment]
This change is now on CRAN.
