### ISSUE TITLE
Wrong 'vctrs' version loading with neonUtilities

### ISSUE THREAD

**Issue by KathleenRuth** [NEONScience/NEON-utilities#74]
I've used neonUtilities many times but started having this error message last night about the wrong vctr version loading.

> install.packages("neonUtilities")
Installing package into ‘C:/Users/Katie's Computer/Documents/R/win-library/3.6’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.6/neonUtilities_1.3.3.zip'
Content type 'application/zip' length 293618 bytes (286 KB)
downloaded 286 KB

package ‘neonUtilities’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\Katie's Computer\AppData\Local\Temp\Rtmp8Uo4qA\downloaded_packages
> library("neonUtilities")
Error: package or namespace load failed for ‘neonUtilities’ in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]):
 namespace ‘vctrs’ 0.2.0 is being loaded, but >= 0.2.1 is required

**Comment by cklunch** [comment]
@KathleenRuth 
This looks like it's just an out of date package locally. Try updating or reinstalling vctrs on your machine, then start a new R session and try to load the neonUtilities library again.

**Comment by cklunch** [comment]
@KathleenRuth 
Were you able to resolve this, or is it still causing problems?

**Comment by KathleenRuth** [comment]
@cklunch I resolved it thank you for your help
