### ISSUE TITLE
Joining phenology data objects

### ISSUE THREAD

**Issue by KathleenRuth** [NEONScience/NEON-utilities#79]
I'm continually receiving an error about date objects while cleaning up phenology data for data product DP1.10055.001

I'm following the phenology/temperature tutorial
https://www.neonscience.org/osis-pheno-temp-series 
the tutorial has been smooth up until this point with this data product. And I converted the columns to date classes...

Thank you for any help or suggestions

see code below: 

>               
> ind_last <- ind_noD %>%
+     group_by(individualID) %>%
+     filter(editedDate==max(editedDate))
>     
> ind_lastnoD <- ind_last %>%
+     group_by(editedDate, individualID) %>%
+     filter(row_number()==1)   
>     
> status_noD <- status %>%
+     group_by(individualID) %>%
+     filter(editedDate==max(editedDate))
>     
> satus_noD <- status %>%
+     group_by(editedDate, individualID) %>%
+     filter(row_number()==1) 
>     

> phe_ind <- left_join(status_noD, ind_lastnoD)
Error: cannot join a Date object with an object that is not a Date object

**Comment by cklunch** [comment]
@KathleenRuth Yes, we've had some issues with that particular tutorial staying up to date as data products have updated. It's not a neonUtilities issue, I think it has to do with naming and formatting in the phenology data product.

@mjones01 I think this one already has a fix in progress?

**Comment by mjones01** [comment]
@KathleenRuth  - Unfortunately we're currently having a website issue where our tutorials edits in GitHub aren't syncing to the NEON website. Our website team is working to fix the issue. 
 @cklunch is correct that this is an error with the current version of the tutorial and not with neonUtilities. You can see the most recent version of the .RMD on my GitHub fork and it will be posted to the website as soon as possible: https://github.com/mjones01/NEON-Data-Skills/blob/master/tutorials/R/NEON-pheno-temp-timeseries/01-explore-phenology-data.Rmd

**Comment by KathleenRuth** [comment]
@mjones01 Thank you for the help. Is there an area within the tutorials github where I can submit further questions?

**Comment by mjones01** [comment]
@KathleenRuth You can use the Issues in the NEONScience/NEON-Data-Skills repo: https://github.com/NEONScience/NEON-Data-Skills
