### ISSUE TITLE
loadByProduct() returns incorrect encoding for Algae taxa, probably other taxonomic groups as well

### ISSUE THREAD

**Issue by sokole** [NEONScience/NEON-utilities#88]
**Function**
loadByProduct

**Describe the bug**
When algae data with taxonomy are downloaded this way, scientificNames with non-standard characters have the incorrect encoding. For example, in alg_taxonomyProcessed, when the taxonID 'NEONDREX6001' is returned in the data set, the scientificName should be "Amphipleura pellucida (Kützing) Kützing", but the function returns "Amphipleura pellucida (KÃ¼tzing) KÃ¼tzing"

**To Reproduce**
```
#packages used
library(dplyr)
library(neonUtilities)


# in 
my_dpid <- "DP1.20120.001"

metadata_all <- neonUtilities::getProductInfo(my_dpid)

landing_page_url <- paste0("https://data.neonscience.org/data-products/", my_dpid)

#################

# Try this:
# only 2 sites, restricted in time
all_tabs_in <- neonUtilities::loadByProduct(
  dpID = "DP1.20166.001", 
  site = c("MAYF", "PRIN"),
  startdate = "2016-1", 
  enddate = "2018-11",  
  package = "expanded", 
  check.size = FALSE)

# view scientificName for taxonID 'NEONDREX6001'
all_tabs_in$alg_taxonomyRaw %>% filter(taxonID == 'NEONDREX6001') %>% slice(1) %>% select(scientificName)

# what I see:
# Amphipleura pellucida (KÃ¼tzing) KÃ¼tzing
```

**Expected behavior**
The above script should return "Amphipleura pellucida (Kützing) Kützing"

**System (please complete the following information):**
Windows 10 Enterprise 
 - OS Version: [e.g. 22]
1909 18363.719
 - R Version: [e.g. 3.5.1]
R version 3.6.3 (2020-02-29)

**Additional context**
I think the scientificNames are correct in the database. When I use restR to lookup scientificNames from the taxonID, they have the correct encoding and format. So I think it's an issue in extracting the text strings from the xml?

**Comment by sokole** [comment]
I can try to tackle this soonish. Mainly posting here to document the issue.

**Comment by cklunch** [comment]
Thanks @sokole ! This was an easy fix in readTableNEON(), fixed on GitHub now.

**Comment by cklunch** [comment]
This fix is now on CRAN.
