### ISSUE TITLE
getReadmePublicationDate seems to output many duplicates of each readme

### ISSUE THREAD

**Issue by eshrh** [NEONScience/NEON-utilities#95]
**Function**
Which of the functions in the neonUtilities package is this bug found in?
stackByTable/getReadmePublicationDate

**Describe the bug**
The stacked readme file contains several duplicate rows of each instance of a readme checked.

**To Reproduce**
Download tick data, DP1.10093.001, over a time range: say 2016-01-01 to 2019-31-1 from OSBS. The readme file, in the post-stacking section, contains 31 unique rows that are repeated 89-90 times each. This leads to a readme file that is about 2,800 lines long in total.

**Expected behavior**
The stacked readme contains only a unique list of the 31 readmes considered.

**System (please complete the following information):**
 - OS: arch gnu/linux
 - OS Version: N/A. Kernel version is 5.7.7
 - R Version: 3.5.1

I might try to submit a patch soon.

**Comment by cklunch** [comment]
@eshrh Thanks for the heads up. @NateMietk Can you look into this?

**Comment by NateMietk** [comment]
@cklunch yup - I can look into this Wednesday or Thursday.

**Comment by cklunch** [comment]
@eshrh This is now fixed on GitHub, thanks @NateMietk ! We'll close the issue when the fix is on CRAN.

**Comment by cklunch** [comment]
@eshrh This fix is now live on CRAN, thanks for letting us know about it!
